import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(dir, "../package.json"), "utf-8"));

writeFileSync(
  resolve(dir, "../src/version.ts"),
  `// Auto-generated by scripts/prebuild.mjs — do not edit manually
export const SDK_VERSION = "${pkg.version}";
`,
);
